export const FILES = [
  { id: 'readme',   name: 'README.md',    icon: 'M',  color: '#519aba', hint: 'Home' },
  { id: 'about',    name: 'about.ts',     icon: 'TS', color: '#4ec9b0', hint: 'About' },
  { id: 'projects', name: 'projects.tsx', icon: 'TX', color: '#f0c674', hint: 'Projects' },
  { id: 'skills',   name: 'stack.json',   icon: '{}', color: '#89d185', hint: 'Skills' },
  { id: 'contact',  name: 'contact.sh',   icon: 'SH', color: '#e8bd80', hint: 'Contact' },
]

export const PROJECTS = [
  {
    id: 'pc1',
    name: 'EventHub',
    icon: '☕',
    iconBg: 'rgba(241,76,76,.1)',
    iconColor: '#f14c4c',
    oneliner: 'Campus event management platform · Full SDLC · Scrum team',
    bullets: [
      'RESTful APIs in Java (Spring Boot) using OOP design patterns',
      'Designed relational MySQL schema, integrated full-stack frontend',
      'Containerised with Docker, CI/CD via GitHub Actions',
      'Unit tests, integration tests, full UAT cycles with defect tracking',
      'Agile/Scrum delivery with a real product owner and milestone reviews',
    ],
    tags: ['Java', 'Spring Boot', 'MySQL', 'Docker', 'GitHub Actions'],
    codeLabel: 'API ENDPOINTS — EventHub',
    codeType: 'api',
    codeData: [
      { method: 'GET',  methodClass: 'method-get',  path: '/api/events',       desc: 'list all' },
      { method: 'POST', methodClass: 'method-post', path: '/api/events',       desc: 'create' },
      { method: 'GET',  methodClass: 'method-get',  path: '/api/events/{id}',  desc: 'get one' },
      { method: 'PUT',  methodClass: 'method-put',  path: '/api/events/{id}',  desc: 'update' },
      { method: 'DEL',  methodClass: 'method-del',  path: '/api/events/{id}',  desc: 'delete' },
      { method: 'POST', methodClass: 'method-post', path: '/api/auth/login',   desc: 'JWT auth' },
    ],
    codeFooter: 'Docker · port 8080 · GitHub Actions CI',
  },
  {
    id: 'pc2',
    name: 'Cloud Music Platform',
    icon: 'PY',
    iconBg: 'rgba(78,201,176,.1)',
    iconColor: '#4ec9b0',
    oneliner: 'Multi-service AWS app · Traced and fixed a production defect via CloudWatch',
    bullets: [
      'Designed full AWS architecture across EC2, S3, Lambda, DynamoDB',
      'Traced silent data failures through CloudWatch logs',
      'Isolated a misconfigured API Gateway mapping, fixed it, added validation',
      'Produced system architecture docs and deployment guides',
    ],
    tags: ['Python', 'AWS EC2', 'S3', 'Lambda', 'DynamoDB', 'API Gateway', 'CloudWatch'],
    codeLabel: 'AWS ARCHITECTURE',
    codeType: 'aws',
    awsNodes: [
      { label: 'API Gateway', badge: 'entry', color: '#4ec9b0' },
      { label: 'AWS Lambda', badge: 'compute', color: '#e0af68' },
      { label: 'DynamoDB', badge: 'db', color: '#bb9af7' },
      { label: 'S3 Bucket', badge: 'storage', color: '#7dcfff' },
      { label: 'CloudWatch', badge: 'monitoring', color: '#9ece6a' },
    ],
  },
  {
    id: 'pc3',
    name: 'Music Genre Classifier',
    icon: 'PY',
    iconBg: 'rgba(181,206,168,.1)',
    iconColor: '#b5cea8',
    oneliner: 'End-to-end ML pipeline · Fixed class imbalance that was killing accuracy',
    bullets: [
      'Built full pipeline: data cleaning → feature engineering → model training → evaluation',
      'Diagnosed a class imbalance issue degrading performance; applied SMOTE to fix it',
      'Evaluated multiple classifiers (Random Forest, SVM, k-NN), selected best performer',
      'Documented findings in Jupyter notebook with visualisations',
    ],
    tags: ['Python', 'scikit-learn', 'pandas', 'SMOTE', 'Jupyter'],
    codeLabel: 'MODEL PERFORMANCE',
    codeType: 'ml',
    mlBars: [
      { label: 'Accuracy', value: 84, w: 84 },
      { label: 'Precision', value: 81, w: 81 },
      { label: 'Recall', value: 79, w: 79 },
      { label: 'F1', value: 80, w: 80 },
    ],
    mlNote: 'After SMOTE class balancing · Random Forest · 5-fold CV',
  },
  {
    id: 'pc4',
    name: 'Social Media App',
    icon: 'JS',
    iconBg: 'rgba(240,198,116,.1)',
    iconColor: '#f0c674',
    oneliner: 'Node.js backend · Real-time features · JWT auth',
    bullets: [
      'RESTful API with Express.js, JWT-based auth, bcrypt password hashing',
      'Post, comment, follow/unfollow, like system with feed generation',
      'SQLite for dev, PostgreSQL-ready schema with migrations',
      'Full test coverage with Jest; documented with Swagger/OpenAPI',
    ],
    tags: ['Node.js', 'Express', 'PostgreSQL', 'JWT', 'Jest'],
    codeLabel: 'API ENDPOINTS — Social',
    codeType: 'api',
    codeData: [
      { method: 'POST', methodClass: 'method-post', path: '/api/auth/register', desc: 'sign up' },
      { method: 'POST', methodClass: 'method-post', path: '/api/auth/login',    desc: 'JWT login' },
      { method: 'GET',  methodClass: 'method-get',  path: '/api/posts/feed',    desc: 'user feed' },
      { method: 'POST', methodClass: 'method-post', path: '/api/posts',         desc: 'create post' },
      { method: 'POST', methodClass: 'method-post', path: '/api/users/:id/follow', desc: 'follow' },
    ],
    codeFooter: 'Express · Jest · OpenAPI docs',
  },
];

export const TIMELINE = [
  {
    title: 'CS (Advanced) Student',
    org: 'RMIT University · Melbourne',
    desc: 'Building across full-stack, cloud, and ML. Graduating July 2026.',
    date: '2022\nPresent',
    hasLine: true,
  },
  {
    title: 'Customer Service Representative',
    org: 'Marvel Stadium · Melbourne',
    desc: 'Front-line support for 1,000+ attendees. Fast decisions, high volume.',
    date: 'May 2025\nPresent',
    hasLine: true,
  },
  {
    title: 'Committee Member, FIRE+',
    org: 'RMIT Social Media Portfolio',
    desc: 'Created content reaching 1,000+ students.',
    date: '2024\nPresent',
    hasLine: true,
  },
  {
    title: "World Scholar's Cup",
    org: 'Global Participant',
    desc: 'Competed internationally. Also: international exchange, Kilgraston School, Scotland.',
    date: '2022',
    hasLine: false,
  },
];
